# Generated by Django 5.2.7 on 2026-03-18 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_image'),
        ('payments', '0003_payment_quote_payment_type_alter_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='type',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('ORDER', 'Commande'), ('QUOTE', 'Devis'), ('DIRECT', 'Vente Directe / Comptant')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='product_direct',
            field=models.ForeignKey(blank=True, help_text='Uniquement pour vente directe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product'),
        ),
        migrations.AddField(
            model_name='payment',
            name='quantity_direct',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='ID transaction ou N° reçu', max_length=100),
        ),
    ]
