# Generated by Django 5.2.7 on 2026-03-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_is_active_delete_productspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_percent',
            field=models.PositiveIntegerField(default=0, help_text='Réduction en pourcentage'),
        ),
    ]
