# Generated by Django 5.2.7 on 2026-03-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
    ]
